server:
  port: 8080  # ← 이게 올바른 설정입니다
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/cram
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: ${SECRET_JWT_KEY}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${SECRET_NAVER_KEY}
            client-secret: l6bKGavqRi
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
              - birthday
              - birthyear

          google:
            client-name: google
            client-id: ${SECRET_GOOGLE_KEY}
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/user.birthday.read

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    com.cram: TRACE  # 전체 로그 TRACE 출력
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{20}] %msg%n"
currentenviroment:
  host: ${ENVIROMENT}