spring:
  jwt:
    secret: eIcXG+itRwOEgz4COWx1ckHsHTB94VCYS+A5plrAXpQNuvZGxQc+/fiP7T4aYOIoxAmX9G7PMJWbjpi4MgYnfA==

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%logger{20}] %msg%n"